### ISSUE TITLE
replace NHDHR source with aws

### ISSUE THREAD

**Issue by jordansread** [USGS-R/lake-surface-temperature-prep#8]
@SimonTopp ran into this. 

Need to update [this](https://github.com/USGS-R/lake-surface-temperature-prep/blob/main/1_crosswalk_fetch/src/fetch_nhdhr.R#L5) to [this](https://github.com/USGS-R/lake-temperature-model-prep/blob/main/1_crosswalk_fetch/src/fetch_NHD.R#L5)

**Comment by SimonTopp** [comment]
Just quick update on this. I poked around a little this week, I think the actual correct path is 
`https://prd-tnm.s3.amazonaws.com/StagedProducts/Hydrography/NHD/State/GDB/NHD_H_%s_State_GDB.zip`.  Re-running on personal drive cache this weekend and will compare to make sure lakes match up.

**Comment by SimonTopp** [comment]
Addressed in #9
